language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - nightly
    - hhvm

matrix:
    allow_failures:
        - php: hhvm
        
branches:
    except:
        - gh-pages
    
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

install:
    - echo $TRAVIS_PHP_VERSION
    - travis_retry composer self-update && composer --version
    - travis_retry composer global require "fxp/composer-asset-plugin:*"
    - export PATH="$HOME/.composer/vendor/bin/:$PATH"
    - travis_retry composer install --prefer-dist --no-interaction
    
before_script:
    - php -r "echo INTL_ICU_VERSION . \"\n\";"
    - php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
    - php -v
    - |
        if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then
            php -m
        fi
    - |
        if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
            PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
        fi
        
script: 
    - phpunit --verbose --debug
        
after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
